### ISSUE TITLE
Error in Better Image Popups and Custom Media Support

### ISSUE THREAD

**Issue by Mef45** [Orrielel/BetterDiscordAddons#1]
```
[BetterDiscord] Unable to fire observer for Better Image Popups.
Error: Cannot read property 'classList' of null
TypeError: Cannot read property 'classList' of null
    at BetterImagePopups.observer (<anonymous>:39:32)
    at PluginModule.rawObserver (https://cdn.rawgit.com/rauenzi/BetterDiscordApp/089741a05df97c1353716e5aab003bf0d9c3c13f/js/main.min.js:52:17721)
    at https://cdn.rawgit.com/rauenzi/BetterDiscordApp/089741a05df97c1353716e5aab003bf0d9c3c13f/js/main.min.js:1:8708
    at Array.forEach (native)
    at MutationObserver.<anonymous> (https://cdn.rawgit.com/rauenzi/BetterDiscordApp/089741a05df97c1353716e5aab003bf0d9c3c13f/js/main.min.js:1:8638)
```

```
[BetterDiscord] Unable to fire observer for Custom Media Support.
Error: Cannot read property 'classList' of undefined
TypeError: Cannot read property 'classList' of undefined
    at CustomMediaSupport.observer (<anonymous>:676:16)
    at PluginModule.rawObserver (https://cdn.rawgit.com/rauenzi/BetterDiscordApp/089741a05df97c1353716e5aab003bf0d9c3c13f/js/main.min.js:52:17721)
    at https://cdn.rawgit.com/rauenzi/BetterDiscordApp/089741a05df97c1353716e5aab003bf0d9c3c13f/js/main.min.js:1:8708
    at Array.forEach (native)
    at MutationObserver.<anonymous> (https://cdn.rawgit.com/rauenzi/BetterDiscordApp/089741a05df97c1353716e5aab003bf0d9c3c13f/js/main.min.js:1:8638)
```

**Comment by Orrielel** [comment]
My bad for responding after 4 days;

I presume this happens when you're previewing an image?

**Comment by Orrielel** [comment]
Should be fixed now :ok_hand:
